/**
 *-----------------------------------------------------------------------------
 * This event handler, handles the impact level event generated by the global
 * simulation timer event. Updates all the variables we want simulated on this
 * app.
 *
 * @author Adolph Seema.
 * @date   2015/05/10
 *
 * @param  {none} -
 *
 * @return {void} - Updates all the variables in the GUI we want simulated
 *-----------------------------------------------------------------------------
 */
//TEMP// $( document ).on(
//TEMP// "sim_impact_level_event",
//TEMP//  function( event, arg1, ag2 ) {
//TEMP//    console.log( arg1 );  //sim_impact_lvl
//TEMP//    console.log( arg2 );  //sim_impact_xyz_acc_array

//TEMP//    //update impact level
//TEMP//    $("#ok_button").removeClass( "btn-green" );
//TEMP//}); //END.sim_tick_event.handler.--------------------------------------

$(document).ready(function(){
  $("#severe_button").click(function(){
      $("#severe_button").toggleClass("btn-red");
  });
});

$( document ).on( "pagecreate", ".jqm-band", function( event ) {
  var page = $( this )

  //console.log( impact_level + "___" + event.data );
  var impact_level = $.getUrlVar('PostData1');

  if ( impact_level == G_SEVERE ) {

    $("#severe_button").addClass("btn-red");

  } else if ( impact_level == G_MODERATE ) {

    $("#moderate_button").addClass("btn-yellow");

  } else if ( impact_level == G_MILD ) {

    $("#mild_button").addClass("btn-blue");

  } else {

    $("#ok_button").addClass("btn-green");

  }

  //stay on the impact page for 30 seconds then go back to where the action is.
  //i.e. the graph-details page.
  setTimeout( function(){
    window.location.href = 'graph-details.html';
  }, 30000 );
});

//--------------------END.OF.DOCUMENT...80.columns.wide------------------------